const config = {
  assetStore: {
    bucketParams: {
      ACL: {},
      Bucket: 'test-automation-asset-store-aws-s3',
      name: 'test-automation-asset-store-aws-s3',
    },
    Policy: {
      Statement: [
        {
          Sid: 'AddPerm',
          Effect: 'Allow',
          Principal: '*',
          Action: ['s3:GetObject'],
          Resource: ['arn:aws:s3:::test-automation-asset-store-aws-s3/*'] // Required
        }
      ]
    },
    // `apiVersion`, `apiKey` and `downloadId` can be generated by using an asset's url pattern
    pattern: '/:apiKey/:uid/:downloadId/:filename'
  }
}

export { config }
